const LOAD_POSTS = "LOAD_POSTS";
const ADD_UPDATE_POST = "ADD_UPDATE_POST";
const DELETE_POST = "DELETE_POST";
const ADD_COMMENT = "ADD_COMMENT";
const DELETE_COMMENT = "DELETE_COMMENT";

export {
  LOAD_POSTS,
  ADD_UPDATE_POST,
  DELETE_POST,
  ADD_COMMENT,
  DELETE_COMMENT
};