const LOAD_POSTS = "LOAD_POSTS";
const ADD_POST = "ADD_POST";
const UPDATE_POST = "UPDATE_POST";
const LOAD_SINGLE_POST = "LOAD_SINGLE_POST";
const DELETE_POST = "DELETE_POST";
const ADD_COMMENT = "ADD_COMMENT";
const DELETE_COMMENT = "DELETE_COMMENT";

export {
  LOAD_POSTS,
  ADD_POST,
  UPDATE_POST,
  LOAD_SINGLE_POST,
  DELETE_POST,
  ADD_COMMENT,
  DELETE_COMMENT
};